// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KvsClient is the client API for Kvs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvsClient interface {
	// Set key-value data
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Get value of the key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type kvsClient struct {
	cc grpc.ClientConnInterface
}

func NewKvsClient(cc grpc.ClientConnInterface) KvsClient {
	return &kvsClient{cc}
}

func (c *kvsClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/Kvs/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Kvs/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvsServer is the server API for Kvs service.
// All implementations must embed UnimplementedKvsServer
// for forward compatibility
type KvsServer interface {
	// Set key-value data
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Get value of the key
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedKvsServer()
}

// UnimplementedKvsServer must be embedded to have forward compatible implementations.
type UnimplementedKvsServer struct {
}

func (UnimplementedKvsServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKvsServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKvsServer) mustEmbedUnimplementedKvsServer() {}

// UnsafeKvsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvsServer will
// result in compilation errors.
type UnsafeKvsServer interface {
	mustEmbedUnimplementedKvsServer()
}

func RegisterKvsServer(s grpc.ServiceRegistrar, srv KvsServer) {
	s.RegisterService(&Kvs_ServiceDesc, srv)
}

func _Kvs_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kvs/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kvs/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kvs_ServiceDesc is the grpc.ServiceDesc for Kvs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kvs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Kvs",
	HandlerType: (*KvsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Kvs_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Kvs_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/kvs.proto",
}
